version: "3.8"

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      # Название сервера
      SERVER_NAME: "Minecraft Server"

      GAMEMODE: "survival"

      DIFFICULTY: "HARD"

      LEVEL_TYPE: "DEFAULT"

      ALLOW_CHEATS: "FALSE"

      MAX_PLAYERS: "10"

      ONLINE_MODE: "true"

      #WHITE_LIST: ""
      VIEW_DISTANCE: "32"

      TICK_DISTANCE: "8"

      PLAYER_IDLE_TIMEOUT: "0"

      MAX_THREADS: "8"

      LEVEL_NAME: "level"

      #LEVEL_SEED: ""
      DEFAULT_PLAYER_PERMISSION_LEVEL: "member"


    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: on-failure