version: '3.8'

services:
  minecraft-bedrock-server:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock-server
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      DIFFICULTY: "hard"           # сложность (peaceful, easy, normal, hard)
      LEVEL_NAME: "MyMinecraftWorld" # название мира
      VIEW_DISTANCE: "32"            # дальность прорисовки (в чанках)
      GAMEMODE: "survival"           # режим игры (survival, creative, adventure)
      MAX_PLAYERS: "10"              # максимальное количество игроков
      ONLINE_MODE: "true"            # проверка учетных записей при входе
      ALLOW_CHEATS: "false"          # разрешение на использование читов
      #WHITELIST: "false"              # включение белого списка игроков
      SERVER_NAME: "BC"        # имя сервера
    volumes:
      - mc-bedrock-data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  mc-bedrock-data:
